### ISSUE TITLE
installing www-p fails because of wrong make argument

### ISSUE THREAD

**Issue by nonchip** [radare/radare2-webui#133]
make for `www-p` as run by the package manager fails because of argument `-c` for "change to directory" while current gnu make expects `-C`

**Comment by radare** [comment]
send a PR

**Comment by nonchip** [comment]
i'll do so tomorrow, it's a bit late where i am.

**Comment by radare** [comment]
ok no hurry, just as a side note, you can create a pullreq without cloning the repo or even using a text editor. just using the github web interface and clicking the pencil icon
