### ISSUE TITLE
merge-stream missing when doing r2pm -i www-p

### ISSUE THREAD

**Issue by ZetaTwo** [radare/radare2-webui#142]
I tried installing the www-p UI by doing
```
r2pm -i www-p
```
which returned an error saying the "merge-stream" package could not be found. (Sorry for no copy-paste, lost the error in scrollback).
I tried doing
```
npm -g install merge-stream
```
and retrying which solved the issue. Does this mean that there is something missing in a requirements entry somewhere?

**Comment by radare** [comment]
Edit the pckage.json

**Comment by ZetaTwo** [comment]
Ok, but is this something that should be added to https://github.com/radare/radare2-webui/blob/master/www/p/package.json then?

**Comment by radare** [comment]
yes

**Comment by gcolajan** [comment]
www-p already contains merge-stream: https://github.com/radare/radare2-webui/commit/6b4ac2496c08a7d278f620b9fb4d497cd56d2609#diff-333dc862311134a0b2a1bf8e2b17c2c0R31

I wasn't able to reproduce the issue.

**Comment by ZetaTwo** [comment]
Ok, then I must have forgot to update or something. Good that it is fixed anyway!
