### ISSUE TITLE
updates for the new css files

### ISSUE THREAD

**Issue by Z-Y00** [radare/radare2-webui#144]
during my install . i got these output
hoping you will update these soon
npm WARN deprecated gulp-clean-css@2.4.0: breaking changes from clean-css 4.x. Please install gulp-clean-css 3.x
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

**Comment by radare** [comment]
can you send a PR upgrading those dependencies in the package.json ? 

thanks

**Comment by Z-Y00** [comment]
Well, i'm not familiar with that but i'll try if i could

**Comment by radare** [comment]
Its just a matter of editing the package.json and upgrade the version numbers with the last ones that "npm outdated" shows.

Thanks!
