### ISSUE TITLE
support with kali

### ISSUE THREAD

**Issue by Z-Y00** [radare/radare2-webui#146]
Well , i'm using kali now. i found it badly supported. 
Although the radare was preinstalled , the web-ui was removed . 

And following the install procedure in readme will install the web ui in "/usr/share/radare2/1.1.0/www/ "
then you need to move the UI's folder to the place radare trying to find, which in kali is "/home/foo-name/.config/radare2/www/"

and there are sometimes output like
 [HTTP] 127.0.0.1:35884 /m/vendors/mdl-selectfield.min.js.map
File '/usr/share/radare2/1.1.0/www//m/vendors/mdl-selectfield.min.js.map' not found

could you require kali-linux to solve these things

**Comment by radare** [comment]
this is a problem with kali linux for packaging and shipping old versions of r2.
