### ISSUE TITLE
Fix colors in /m

### ISSUE THREAD

**Issue by radare** [radare/radare2-webui#44]
There are several problems in /m with the colors right now. the color scheme is probably not the best one which brings some issues:

* [ ] blue lines in graph are not visible
* [ ] some panels must be in black and others in white
* [ ] there's no easy way for the user to change the r2 color palete (and save it for later) from /m
* [ ] the pink buttons contrast too much with the rest of turqoise and grey colors
* [ ] the settings panel should contain options to configure all this stuff

**Comment by radare** [comment]
MDL theme can be generated in this webpage https://getmdl.io/customize/

**Comment by Maijin** [comment]
#38

**Comment by radare** [comment]
Looks quite better now, let's close this for now
