### ISSUE TITLE
shlr/www is not maintainable

### ISSUE THREAD

**Issue by Maijin** [radare/radare2-webui#7]
Current graphs doesnt work  in Chrome because this is the only browser that have deprecated a specific javascript function to manipulate SVG required by joint.js. Trying to upgrade joint.js results in a complete hell of javascript dependencies that break other stuff.

This is also problematic for the distro packagers which have to be careful when including random .js files that have non-lgpl compatible licenses like the joint.js

* [x] Keep only one single, self-written without dependencies, UI in r2 (i vote for the  material one)
* [x] Use bower/browserify/... to maintain js deps like jquery, joint
* [x] Use grunt/bypp instead of makefiles to generate the uglified files
* [x] Update all enyo/joint/jquery/jquery-ui/material/.. dependencies
* [x] Make them available via r2pm

From https://github.com/radare/radare2/issues/4181

**Comment by radare** [comment]
yay \o/

**Comment by XVilka** [comment]
Why it's blinking?

**Comment by radare** [comment]
wat
