### ISSUE TITLE
Vertical split glitch in safari

### ISSUE THREAD

**Issue by radare** [radare/radare2-webui#89]
<img width="940" alt="screen shot 2016-08-23 at 20 33 06" src="https://cloud.githubusercontent.com/assets/917142/17904744/d85cfc7a-6970-11e6-9e5a-114f2fdddca8.png">

**Comment by gcolajan** [comment]
Can't reproduce on other browsers (can't run Safari)

**Comment by radare** [comment]
seems fixed in master
