### ISSUE TITLE
Make hexdump offsets and values clickable in /m

### ISSUE THREAD

**Issue by radare** [radare/radare2-webui#92]

**Comment by gcolajan** [comment]
I can make flags clickable (going to disasm?) but for the offsets, there is a double-click event plugged to select the whole line, what should we do?

**Comment by radare** [comment]
maybe differentiate the offset from the address of the instruction?

**Comment by gcolajan** [comment]
Maybe we can simply bind this on a wheel click / long tap? Don't know if it would feel intuitive...

**Comment by radare** [comment]
also the 32bit values should be clickable too (when readidng the stack you use to find valid 32/64bit addresses that may be clickable)
